#!/bin/bash
#
# Target dist: Ubuntu xenial
DIST=xenial

rm -rf ${DIST}
cp -r debian ${DIST}

echo "pyaml python-yaml" >> ${DIST}/pydist-overrides

wrap-and-sort -sat -d ${DIST}

# clean backports scripts
rm -rf ${DIST}/backports
exit 0
